# Generated by Django 5.0.6 on 2024-09-11 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tuitions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('grade', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('HSC-1st Year', 'HSC-1st Year'), ('HSC-2nd Year', 'HSC-2nd Year'), ('Admission Test', 'Admission Test')], max_length=100)),
                ('medium', models.CharField(choices=[('Bangla', 'Bangla'), ('English', 'English')], max_length=10)),
                ('prefered_tutor', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('stu_gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10)),
                ('salary', models.IntegerField()),
                ('descripition', models.TextField()),
                ('location', models.CharField(max_length=300)),
                ('have_tuitor', models.BooleanField(default=False)),
                ('is_applied', models.BooleanField(default=False)),
                ('extra_need', models.TextField(default='Null')),
                ('subjects', models.ManyToManyField(related_name='subject', to='tuitions.subjects')),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('rating', models.CharField(choices=[('⭐', '⭐'), ('⭐⭐', '⭐⭐'), ('⭐⭐⭐', '⭐⭐⭐'), ('⭐⭐⭐⭐', '⭐⭐⭐⭐'), ('⭐⭐⭐⭐⭐', '⭐⭐⭐⭐⭐')], max_length=100)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.usermodel')),
                ('tuition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuitions.tuitions')),
            ],
        ),
    ]
