# Generated by Django 5.0.6 on 2024-09-11 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_usermodel_profile_pic_alter_usermodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='profile_pic',
            field=models.ImageField(default='', upload_to='user/images'),
        ),
    ]
