# Generated by Django 5.0.6 on 2024-09-27 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_usermodel_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='profile_pic',
        ),
    ]
